# -*- coding: utf-8 -*-
"""Ml microproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KrtHcWY7-HiMkGNNKIIbwHdCm5hiJRA
"""

# train_model.py
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pickle

# Load dataset
data = pd.read_csv('heart.csv')
# Features and labels
X = data.drop('target', axis=1)
y = data['target']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Save model
with open('heart_model.pkl', 'wb') as f:
    pickle.dump(model, f)